---
title: "Untitled"
output: html_document
date: "2024-08-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(amerifluxr)
library(pander)
library(REddyProc)
library(lubridate)
library(tidyverse)
library(bigleaf)
library(data.table)
```

# read in data 
```{r}
setwd(data_dir)
base_df = fread("data_for_gapfilling_BART_AmeriFlux.csv")
```

# intialize EProc
```{r}
EddyData <- filterLongRuns(base_df, "NEE")
EddyData$Year <- as.numeric(EddyData$Year)
EddyData$Hour <- as.numeric(EddyData$Hour)
EddyData$DoY <- as.numeric(EddyData$DoY)

EddyDataWithPosix <- fConvertTimeToPosix(EddyData, 'YDH',Year = 'Year', Day = 'DoY', Hour  = 'Hour')
head(EddyDataWithPosix$DateTime)
EProc <- sEddyProc$new('US-Bar', EddyDataWithPosix, c('NEE','Rg','Tair','VPD', 'Ustar'))
EProc$sSetLocationInfo(LatDeg = 44.0646, LongDeg = -71.2881, TimeZoneHour = -5)
```
# gapfilling before u* filtering 
```{r}
EProc$sMDSGapFill('NEE') # gap-filling before u* filtering
EProc$sDATA
```

# IQR filtering (twice)
```{r}
# Calculate residuals and identify outliers
residual <- EProc$sTEMP$NEE_orig - EProc$sTEMP$NEE_fall
IQR <- IQR(residual, na.rm = TRUE)
outlier <- ifelse(abs(residual) > (IQR * 6), 1, 0)

# Create data frame
EddieC <- data.frame(
  sDateTime = EProc$sTEMP$sDateTime,
  NEE_orig = EProc$sTEMP$NEE_orig,
  Ustar = EProc$sDATA$Ustar,
  NEE_fall = EProc$sTEMP$NEE_fall,
  residual = residual,
  outlier = outlier
)

# Rename columns
colnames(EddieC) <- c('sDateTime', 'NEE_orig', 'Ustar', 'NEE_fall', 'residual', 'outlier')

# Filter out outliers
EddieC$NEE_filt <- dplyr::if_else(EddieC$outlier > 0, NA_real_, EddieC$NEE_orig)
EddieC$year <- substr(EddieC$sDateTime, 1, 4)
EddieC$doy <- strftime(EddieC$sDateTime, format = "%j")

# Re-run the outlier test after initial filtering
EddieC$residual2 <- EddieC$NEE_filt - EddieC$NEE_fall
EddieC$IQR2 <- IQR(EddieC$residual2, na.rm = TRUE)
EddieC$outlier2 <- ifelse(abs(EddieC$residual2) > EddieC$IQR2 * 6, 1, 0)
EddieC$NEE_filt2 <- ifelse(EddieC$outlier2 == 0, EddieC$NEE_filt, NA)

# Remove outliers from the main data
EProc$sDATA$NEE <- EddieC$NEE_filt2
tail(EProc$sDATA)
```

# Use single ustar scenario
```{r}
uStarTh<- EProc$sEstUstarThresholdDistribution(nSample = 1000L, probs = c(0.05, 0.5, 0.95)) 
EProc$sGetUstarScenarios() # by default, annual u* is used
# EProc$useSeaonsalUStarThresholds()# use seasonal u*
# EProc$useAnnualUStarThresholds() # use annual u*

uStar <- uStarTh  %>%
  filter( aggregationMode == "single") %>%
  select( "uStar", "5%", "50%", "95%")
uStarDf <- cbind(season=na.omit(unique(uStarTh$season)), uStar )
EProc$sSetUstarScenarios(uStarDf)
EProc$sGetUstarScenarios()
```
## gapfill using MDS
```{r}
EProc$sMDSGapFillUStarScens('NEE')
```
## save output
```{r}
FilledEddyData <- EProc$sExportResults()
CombinedData <- cbind(EddyData, FilledEddyData)
save_data = as.data.frame(CombinedData)
fwrite(save_data, "MDS_filled_BART_AmeriFlux.csv")
```

